-- AlterTable
ALTER TABLE `company` ADD COLUMN `isEventCorporate` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `isEventSocials` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `isPolityPayment` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `isReturnMoney` INTEGER NOT NULL DEFAULT 0;
